title: TTRPG
description: Table top role playing game
baseurl: "/" # the subpath of your site, e.g. /blog
#url: "https://example.com" # the base hostname & protocol for your site, e.g. http://example.com
theme: jekyll-theme-minimal
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
include: 
  - _content 
  - _framework